### ISSUE TITLE
Redact list of images

### ISSUE THREAD

**Issue by marySalvi** [DigitalSlideArchive/ImageDePHI#121] opened 2023-05-26 15:32 UTC
Allow a user to indicate a list of images to redact instead of the entire directory perhaps something like:

```
imagedephi run [inputpath] --imageList [array of images]
```

**Comment by manthey** [comment] 2023-05-29 12:36
Would it make more sense to just allow standard globbing and multiple input paths?

**Comment by brianhelba** [comment] 2023-05-29 12:43
This seems like a duplicate of #101

**Comment by manthey** [comment] 2024-10-22 14:11
Closed as being covered by #101.

**Closed by manthey** 2024-10-22 14:11 UTC
